@startjson
{
  "activeTaskName": "where I use Persist",
  "tasks": [
    {
      "name": "default",
      "files": []
    },
    {
      "name": "Version",
      "files": [
        {
          "filepath": "/package.json",
          "lineNumbers": [
            4
          ]
        },
        {
          "filepath": "/CHANGELOG.md",
          "lineNumbers": [
            4
          ]
        }
      ]
    },
    {
      "name": "where I use Persist",
      "files": [
        {
          "filepath": "/src/Persist.ts",
          "lineNumbers": [
            13
          ]
        },
        {
          "filepath": "/src/Models.ts",
          "lineNumbers": [
            15
          ]
        },
        {
          "filepath": "\\src\\Persist.ts",
          "lineNumbers": [
            19,
            34
          ]
        },
        {
          "filepath": "\\src\\TaskManager.ts",
          "lineNumbers": [
            33,
            52
          ]
        },
        {
          "filepath": "\\src\\tasklineNumbers.test.txt",
          "lineNumbers": [
            2,
            8
          ]
        }
      ]
    },
    {
      "name": "taskMarks",
      "files": []
    }
  ]
}
@endjson
